### ISSUE TITLE
Fix Test run configuration 

### ISSUE THREAD

**Issue by frankiecerk** [vgramer/opa-idea-plugin#47]
In files starting with test_, launching a run configuration doesn't seem to work, the Run window just logs the error "Testing Framework quit unexpectedly". Editing the run configuration does not open a window

Additionally, per discussion in pr #28, we don't want to discriminate test configurations based on file name, any rule starting with test_ should be able to launch a test run, regardless of filename

**Comment by frankiecerk** [comment]
The issue with test configurations was user error :) it seems the test configuration doesn't require a bundle to be specified (unlike the eval configurations) and when its not, the test just crashes. I believe we just need to require it as its required in setting up the eval runconfigs @vgramer is this attainable/should I work on this or would you like to?

**Comment by vgramer** [comment]
> we don't want to discriminate test configurations based on the file name, any rule starting with test_ should be able to launch a test run, regardless of filename 

You totally right I was thinking that only the files starting with `test_` were taken  into account by the test command but it not the case

>  it seems the test configuration doesn't require a bundle to be specified (unlike the eval configurations) and when it's not, the test just crashes. I believe we just need to require it as its required in setting up the eval runconfigs 

Look good to me.

Moreover, we should also improve to the error message when the command the failed (eg if we pass a parameter that does not exist or if we can not parse the opa output.) But its a bit tricky... I will open another issue for that

I think we can handle these two points first, it seems to be easy to fix and have good user impact

**Comment by vgramer** [comment]
@frankiecerk I have some free time so I will take this issue :)
