### ISSUE TITLE
marks foo().bar as invalid

### ISSUE THREAD

**Issue by grosser** [vgramer/opa-idea-plugin#57]
```rego
package k8simagepolicy

input_containers {
  c = foo().bar
}
```

<img width="255" alt="Screen Shot 2020-09-29 at 3 28 30 PM" src="https://user-images.githubusercontent.com/11367/94623177-7653f480-0268-11eb-85b2-ed69a90ed5f7.png">

**Comment by vgramer** [comment]
ok,  we will look into it. In the meantime, you can split the expression into 2 parts to pass parsing

```
package k8simagepolicy

input_containers {
  c = foo()
  d := c.bar
}
```

**Comment by grosser** [comment]
thx for fixing! :D
