### ISSUE TITLE
Operator inside of function args reported as error

### ISSUE THREAD

**Issue by anderseknert** [vgramer/opa-idea-plugin#63]
# Actual Behavior

`x := count({"x"} & {"y"})`

`&` is reported as an error.

# Expected  Behavior

It shouldn't be.

Note that the `&` is just an example. I could just as well be `|` or another allowed operator.

**Comment by vgramer** [comment]
@anderseknert thanks for catching this bug. I took a quick look at the grammar and I think
replacing
```
expr-call       ::= var ref-arg-dot* "(" ( term ( "," term )* )? ")"
```
 by 
```
term-or-infix-op        ::= term (infix-operator term)?
expr-call                     ::= var ref-arg-dot* "(" ( term-or-infix-op ( "," term-or-infix-op )* )? ")"
```
in the grammar will fix the problem. 

Moreover, this issue reminds me that I don't think we have a TU that ensures we can pass complex arg to a function (eg another function). If you have other test cases that may be related let me know.  I. will push a pr by this evening

**Comment by anderseknert** [comment]
Thanks @vgramer 👍 My other tests (function call in args, etc) all look like they work already but I'll do some more testing in the weekend and will let you know if I encounter any problems. Great work on the plugin!
