### ISSUE TITLE
OPA check file

### ISSUE THREAD

**Issue by asadali** [vgramer/opa-idea-plugin#7]
• invoke `opa check` on active text editor’s contents
  • only check rego files
  • displays errors if any else optionally displays an OK message or nothing
  • ref: [activateCheckFile()](https://github.com/tsandall/vscode-opa/blob/0b8c9e54e4fcce788d8c1dd3dc2b808a5204d3de/src/extension.ts#L165)

**Comment by frankiecerk** [comment]
View commit "opa checkfunctionality + support for general console window"
