### ISSUE TITLE
Grammar: Dynamic imports

### ISSUE THREAD

**Issue by anderseknert** [vgramer/opa-idea-plugin#81]
# Actual Behavior

Error reported for

```rego
import data[input.domain]["some"]["package"]
```

# Expected  Behavior

It should be possible to have non-static components like `input` as part of imports.

# How To Reproduce

```rego
import data[input.domain]["some"]["package"]
```

**Comment by vgramer** [comment]
@anderseknert  which version of opa do you use ? 

when I run `opa check` with version `0.24.0` or `0.25.2` I have the following error 


```
$ cat b.rego
package main
import data[input.domain]["some"]["package"]

$ opa check b.rego
1 error occurred during loading: b.rego:2: rego_parse_error: unexpected ref token: expecting string
	import data[input.domain]["some"]["package"]
```

**Comment by anderseknert** [comment]
My mistake - was thinking of just refering to `data[input.domain]["some"]["package"]` directly, which seems to work. Sorry!
